homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit

###########
##Enables##
###########

frontend:
discovery:
conversation:
history:
logbook:
sun:

##########
##Setups##
##########

http:
  api_password: !secret http_password

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  username: pi
#  password: raspberry

nest:
  username: !secret email
  password: !secret nest_psswd

climate:
  platform: nest

light:
  platform: lifx

joaoapps_join:
  - name: 'android'
    device_id: group.android
    api_key: !secret join_api

lametric:
  host: 192.168.1.171
  api_key: !secret lam_key
